# Generated by Django 5.2.4 on 2025-07-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='certicate_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
