# Generated by Django 5.1.4 on 2025-04-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_deleted',
        ),
    ]
