# Generated by Django 5.1.4 on 2025-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0002_remove_leaverequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
