# Generated by Django 5.2.3 on 2025-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0003_alter_assertstock_allocated_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertstock',
            name='allocated_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Mouse', 'Mouse'), ('Charger', 'Charger'), ('Headphone', 'Headphone')], max_length=50, null=True),
        ),
    ]
