# Generated by Django 5.1.7 on 2025-04-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0003_leaverequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertstock',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sims.department', to_field='department'),
        ),
        migrations.AddField(
            model_name='domain',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sims.department', to_field='department'),
        ),
    ]
