# Generated by Django 5.1.7 on 2025-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0004_assertstock_department_domain_department'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('domain', 'department'), name='unique_domain_per_department'),
        ),
    ]
