# Generated by Django 5.2.4 on 2025-07-29 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0005_alter_assertstock_allocated_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='AttendanceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_period', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_day_type', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10)),
                ('from_half_day_type', models.CharField(blank=True, choices=[('first', 'First Half'), ('second', 'Second Half')], default='first', max_length=10, null=True)),
                ('to_day_type', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10)),
                ('to_half_day_type', models.CharField(blank=True, choices=[('first', 'First Half'), ('second', 'Second Half')], default='first', max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
