# Generated by Django 5.1.4 on 2025-04-24 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0005_domain_unique_domain_per_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegedetails',
            old_name='location',
            new_name='college_address',
        ),
        migrations.RenameField(
            model_name='collegedetails',
            old_name='reg_no',
            new_name='college_emailid',
        ),
        migrations.AddField(
            model_name='collegedetails',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='collegedetails',
            name='college_faculty_phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegedetails',
            name='degree_type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='first_Graduation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collegedetails',
            name='year_of_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
