# Generated by Django 5.2.4 on 2025-07-29 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0006_alter_documentversion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ATTENDANCE_CLAIM', 'Attendance Claim'), ('ATTENDANCE_CLAIM_APPROVED', 'Attendance Claim Approved'), ('ATTENDANCE_CLAIM_REJECTED', 'Attendance Claim Rejected'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
