# Generated by Django 5.1.4 on 2025-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0007_alter_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertstock',
            name='allocated_Assets',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mouse', 'Mouse'), ('Charger', 'Charger'), ('Headphone', 'Headphone')], max_length=50, null=True),
        ),
    ]
