# Generated by Django 5.0 on 2025-07-29 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sims", "0007_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendanceclaim",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="attendanceclaim",
            old_name="review_notes",
            new_name="comments",
        ),
        migrations.RenameField(
            model_name="attendanceclaim",
            old_name="date",
            new_name="from_date",
        ),
        migrations.RemoveField(
            model_name="attendanceclaim",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="attendanceclaim",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="attendanceclaim",
            name="claim_type",
        ),
        migrations.RemoveField(
            model_name="attendanceclaim",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="attendanceclaim",
            name="reason",
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="for_period",
            field=models.CharField(default="july 24", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="from_day_type",
            field=models.CharField(
                choices=[("full", "Full Day"), ("half", "Half Day")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="from_half_day_type",
            field=models.CharField(
                blank=True,
                choices=[("first", "First Half"), ("second", "Second Half")],
                default="first",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="to_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="to_day_type",
            field=models.CharField(
                choices=[("full", "Full Day"), ("half", "Half Day")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendanceclaim",
            name="to_half_day_type",
            field=models.CharField(
                blank=True,
                choices=[("first", "First Half"), ("second", "Second Half")],
                default="first",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendanceclaim",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceclaim",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_attendance_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendanceclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PartialCompletionCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasks_completed",
                    models.ManyToManyField(related_name="certificates", to="Sims.task"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partial_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
