# Generated by Django 5.1.4 on 2025-04-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0008_assertstock_allocated_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assertstock',
            old_name='allocated_Assets',
            new_name='allocated_type',
        ),
    ]
