# Generated by Django 4.2.23 on 2025-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0008_alter_attendanceclaim_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='shift_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
