# Generated by Django 4.2.23 on 2025-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0009_userdata_shift_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='domain',
        ),
        migrations.AddField(
            model_name='userdata',
            name='domain',
            field=models.ManyToManyField(blank=True, to='Sims.domain'),
        ),
    ]
