# Generated by Django 5.1.4 on 2025-04-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0009_rename_allocated_assets_assertstock_allocated_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assertissue',
            old_name='allocated_Assets',
            new_name='allocated_type',
        ),
    ]
