# Generated by Django 5.1.4 on 2025-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0010_rename_allocated_assets_assertissue_allocated_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='aadhar_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
