# Generated by Django 5.1.4 on 2025-04-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0011_alter_personaldata_aadhar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegedetails',
            name='college_emailid',
        ),
        migrations.AddField(
            model_name='collegedetails',
            name='college_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
