# Generated by Django 5.1.4 on 2025-05-02 04:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0012_remove_collegedetails_college_emailid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='check_in',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sims.temp'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='reason',
            field=models.CharField(blank=True, choices=[('LIVE_ON', 'Live on'), ('LIVE_OFF', 'Live off'), ('START_BREAK', 'Start Break'), ('END_BREAK', 'End Break'), ('END_LUNCH', 'End Lunch'), ('START_LUNCH', 'Start Lunch'), ('END_OF_SHIFT', 'End of Shift'), ('START_OTHERS', 'Start Others'), ('END_OTHER', 'End Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AssertAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned'), ('REPAIR', 'Repair'), ('ADDED', 'Added'), ('REPAIR_RETURNED', 'Repair returned'), ('ALRIGHT', 'Alright')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sims.assertstock')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sims.temp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEntries',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, choices=[('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('END_OF_SHIFT', 'End of Shift'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Sims.attendance')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sims.temp')),
            ],
        ),
    ]
