# Generated by Django 5.2.3 on 2025-06-27 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0013_rename_check_in_attendancelog_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('completion', 'Completion Certificate'), ('offer', 'Offer Letter')], max_length=20)),
                ('sent_date', models.DateField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sims.temp')),
            ],
        ),
    ]
