# Generated by Django 5.2.4 on 2025-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0014_certificatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'In Progress'), ('yettojoin', 'Yet to Join'), ('holdandwait', 'Hold and Wait'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
    ]
