# Generated by Django 5.2.4 on 2025-07-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0015_alter_userdata_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('yettojoin', 'Yet to Join'), ('holdandwait', 'Hold and Wait'), ('discontinued', 'Discontinued'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
    ]
