# Generated by Django 5.2.3 on 2025-07-18 07:16

import Sims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0016_alter_userdata_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=Sims.models.document_upload_path),
        ),
    ]
