# Generated by Django 5.2.4 on 2025-07-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0017_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
    ]
