# Generated by Django 5.2.4 on 2025-07-19 17:19

import Sims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sims', '0018_remove_document_created_at_remove_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=Sims.models.document_upload_path),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
